#!/usr/bin/env python3
"""
Robin AI - Report Generator Module
Generates professional OSINT investigation reports in Markdown/HTML format.
"""

import os
import json
import logging
from datetime import datetime
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates structured OSINT investigation reports."""

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_markdown(
        self,
        query: str,
        refined_query: str,
        results: List[Dict],
        analysis: Dict,
        scraped_content: Optional[List[Dict]] = None,
        timing: Optional[Dict] = None,
        tor_ip: Optional[str] = None,
    ) -> str:
        """
        Generate a comprehensive markdown investigation report.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        total_sources = len(results)
        total_unique = len(set(r.get("url", "") for r in results))

        report = f"""# Robin AI - Dark Web OSINT Investigation Report

---

## 📋 Executive Summary

**Investigation Query:** `{query}`
**Refined Query:** `{refined_query}`
**Date/Time:** {timestamp}
**Tor Exit IP:** {tor_ip or 'Unknown'}
**Sources Scanned:** {total_sources} results from {total_unique} unique URLs

### Severity Assessment
**Overall Severity:** {analysis.get('severity', 'Unknown').upper()}
**Threats Identified:** {len(analysis.get('threats_found', []))}

---

## 🎯 Investigation Scope

**Primary Target:** {query}

**Methodology:**
1. Query refinement via Mistral AI LLM
2. Parallel dark web search across 16 search engines
3. Results aggregation and deduplication
4. Onion site content scraping via Tor
5. AI-powered analysis and threat identification
6. Report generation

---

## 🔍 Key Findings

"""
        threats = analysis.get('key_findings', analysis.get('threats_found', []))
        if threats:
            for i, finding in enumerate(threats[:20], 1):
                report += f"### {i}. {finding if isinstance(finding, str) else finding.get('description', str(finding))}\n\n"
        else:
            report += "No specific threats identified in the search results.\n\n"

        report += """## 📊 Search Results Summary

| # | Title | Source | URL |
|---|-------|--------|-----|
"""
        for i, r in enumerate(results[:30], 1):
            title = r.get("title", "Untitled")[:80]
            source = r.get("source", "Unknown")
            url = r.get("url", "")[:100]
            report += f"| {i} | {title} | {source} | {url} |\n"

        if scraped_content:
            report += """
---

## 🕵️ Scraped Content Analysis

"""
            for sc in scraped_content[:10]:
                title = sc.get("title", "Untitled")[:80]
                url = sc.get("url", "")
                content = sc.get("content", "")[:500]
                emails = sc.get("emails", [])
                btc = sc.get("btc_addresses", [])
                eth = sc.get("eth_addresses", [])

                report += f"### [{title}]({url})\n\n"
                report += f"**Content Preview:**\n```\n{content}\n```\n\n"
                if emails:
                    report += f"**Emails Found:** {', '.join(emails[:10])}\n\n"
                if btc:
                    report += f"**BTC Addresses:** {', '.join(btc[:5])}\n\n"
                if eth:
                    report += f"**ETH Addresses:** {', '.join(eth[:5])}\n\n"

        report += """---

## 💡 Recommendations

"""
        recommendations = analysis.get('recommendations', [])
        if recommendations:
            for rec in recommendations:
                rec_text = rec if isinstance(rec, str) else rec.get('text', str(rec))
                report += f"- {rec_text}\n"
        else:
            report += "- Monitor the identified sources for changes\n"
            report += "- Consider expanding the search with related keywords\n"
            report += "- Investigate any credential leaks or exposures found\n"

        report += """
---

## ⚙️ Methodology

- **Tool:** Robin AI-Powered Dark Web OSINT
- **LLM Engine:** Mistral AI (real API)
- **Proxy Network:** Tor (SOCKS5h)
- **Search Engines Queried:** 16 dark web engines
- **Scraping Engine:** BeautifulSoup + lxml
- **Analysis:** Mistral AI LLM-based threat analysis

---

*Report generated by Robin AI OSINT Tool • {timestamp}*
"""

        return report

    def save_report(self, query: str, content: str) -> str:
        """Save report to file and return the filepath."""
        safe_name = "".join(c if c.isalnum() or c in " _-" else "_" for c in query)[:50]
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"robin_report_{safe_name}_{timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"Report saved: {filepath}")
        return filepath